name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Step 1. Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Step 2. Set up JDK 17 ğŸ“¦
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Step 2. Build with Maven ğŸ—ï¸
        run: mvn -B package --file pom.xml

      - name: Step 3. Publish Artifact ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: Granny
          path: target/*.jar